name: deploy-multi-env.yml

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9

    steps:
      - name: Checkout code from main branch
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: pip install boto3

      - name: deploy_staging
        if: github.ref == 'refs/heads/staging'
        needs: deploy
        steps:
          - name: Use AWS credentials stored in ${{ secrets.AWS_STAGING_KEY }} and ${{ secrets.AWS_STAGING_SECRET }}
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_STAGING_KEY }}
              aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET }}
              aws-region: us-east-1
          
          - name: Configure environment variables for staging deployment using boto3
            run: python configure_env.py staging

      - name: deploy_production
        if: github.ref == 'refs/heads/master'
        needs: deploy
        steps:
          - name: Use AWS credentials stored in ${{ secrets.AWS_PRODUCTION_KEY }} and ${{ secrets.AWS_PRODUCTION_SECRET }}
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_PRODUCTION_KEY }}
              aws-secret-access-key: ${{ secrets.AWS_PRODUCTION_SECRET }}
              aws-region: us-east-1
          
          - name: Configure environment variables for production deployment using boto3
            run: python configure_env.py production