

name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        uses: actions/checkout@v2
      - name: Enforce code coverage report
        run: |
          if [ -n "$(git diff HEAD~ --name-only | grep '.js$')" ]; then
            npm run coverage
          fi
      - name: Verify code linting and unit tests
        run: |
          if [ -n "$(git diff HEAD~ --name-only | grep '.js$')" ]; then
            npm run lint
            npm test
          fi
      - name: Complete job
        run: echo "Job completed successfully."