

name: branch-protection.yml
on:
  push:
    branches:
      - main
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | ifneq (echo "No code changes detected")
      - name: Enforce code coverage report
        run: |
          npm install -g codecov
          npm run test
          codecov
      - name: Verify code linting and unit tests
        run: |
          npm install -g eslint
          npm test
      - name: Complete job
        run: |
          echo "Job completed successfully"